[#ftl]
[@b.head/]
[@b.grid items=bills var="bill"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="wallet.inpatient.code" title="住院号"]${bill.wallet.inpatient.code}[/@]
    [@b.col property="wallet.inpatient.name" title="姓名"]${bill.wallet.inpatient.name}[/@]
    [@b.col width="10%" property="wallet.inpatient.feeOrigin.name" title="费用类别"/]
    [@b.col width="8%" property="wallet.inpatient.gender.name" title="性别"/]
    [@b.col width="8%" property="wallet.inpatient.ward.name" title="病区"/]
    [@b.col width="5%" property="wallet.inpatient.bedNo" title="床号"/]
    [@b.col width="8%" property="amount" title="支出金额"/]
    [@b.col width="8%" property="wallet.walletType" title="账户类型"]${bill.wallet.walletType.name}[/@]
    [@b.col width="8%" property="goods" title="消费明细"/]
    [@b.col width="18%" property="payAt" title="入账时间"]
      ${bill.payAt?string('yyyy-MM-dd HH:mm')}
    [/@]
  [/@]
[/@]
[@b.foot/]
