[#ftl]
[@b.head/]
[@b.toolbar title="陪护费信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(attendFee) theme="list"]
    [#if attendFee.persisted]
      [@b.field label="病人"]
        ${attendFee.inpatient.code} ${attendFee.inpatient.name}
        [@b.field label="当前余额"]${attendFee.balance}元[/@]
      [/@]
    [#else]
      [@b.textfield name="attendFee.inpatient.code" label="住院号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.date name="attendFee.createdOn" label="起始年月" value=attendFee.createdOn! required="true" /]
    [@b.textfield name="attendFee.initBalance" label="起始余额" value=attendFee.initBalance! required="true" comment="元"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
