[#ftl]
[@b.head/]
[@b.toolbar title="修改性别类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(cardType) theme="list"]
    [@b.textfield name="cardType.code" label="代码" value="${cardType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="cardType.name" label="名称" value="${cardType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="cardType.enName" label="英文名称" value="${cardType.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="cardType.beginOn,cardType.endOn" required="false,false"
      start=cardType.beginOn end=cardType.endOn format="date"/]
    [@b.textfield name="cardType.remark" label="备注" value="${cardType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
