[#ftl]
[@b.head/]
[@b.toolbar title="住院押金"]bar.addBack();[/@]
  [@b.form action=b.rest.save(deposit) theme="list"]
    [#if deposit.persisted]
      [@b.field label="病人"]
        ${deposit.inpatient.code} ${deposit.inpatient.name}
        [@b.field label="当前余额"]${deposit.amount}元[/@]
        [@b.field label="支付时间"]${deposit.payAt?string("yyyy-MM-dd")}[/@]
      [/@]
    [#else]
      [@b.textfield name="deposit.inpatient.code" label="住院号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.textfield name="deposit.amount" label="金额" value=deposit.amount! required="true" comment="元"/]
    [#if deposit.persisted]
     [@b.date name="deposit.refundAt" label="退回日期" value=deposit.refundAt! required="true" format="datetime"/]
    [/#if]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
