[#ftl]
[@b.head/]
[@b.toolbar title="零用金支出信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(bill) theme="list"]
    [#if bill.persisted]
      [@b.field label="病人"]
        ${bill.wallet.inpatient.code} ${bill.wallet.inpatient.name}
      [/@]
    [#else]
      [@base.inpatient name="inpatient.id" value=(income.wallet.inpatient)! label="病人" required="true"/]
    [/#if]
    [@b.textfield name="bill.amount" label="消费金额" value=bill.amount! required="true" maxlength="20" comment="元"/]
    [@b.date name="payAt" label="入账时间" value=bill.payAt! format="datetime" required="true" /]
    [@b.textfield name="bill.goods" label="消费明细" value=bill.goods! required="true" maxlength="20"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
