[#ftl]
[@b.head/]
[@b.toolbar title="零用金支出信息"]bar.addBack();[/@]

  [#assign enumGoods={'转伙食费和住院费':'转伙食费和住院费','转伙食费':'转伙食费','转住院费':'转住院费','随心E购':'随心E购','出院退款':'出院退款','其他用途':'其他用途'}/]
  [#assign detail_good=""/]
  [#assign enum_good="其他用途"/]
  [#if bill.goods??]
    [#if enumGoods[bill.goods]??]
      [#assign enum_good=bill.goods/]
    [#else]
      [#assign detail_good=bill.goods/]
    [/#if]
  [/#if]

  [@b.form action=b.rest.save(bill) theme="list"]
    [#if bill.persisted]
      [@b.field label="病人"]
        ${bill.wallet.inpatient.code} ${bill.wallet.inpatient.name}
      [/@]
    [#else]
      [@base.inpatient name="inpatient.id" value=(income.wallet.inpatient)! label="病人" required="true"/]
    [/#if]

    [@b.textfield name="bill.amount" label="消费金额" value=bill.amount! required="true" maxlength="20" comment="元"/]
    [@b.date name="payAt" label="入账时间" value=bill.payAt! format="datetime" required="true" /]
    [@b.radios label="消费明细" name="enum_good" items="转伙食费和住院费:转伙食费和住院费,转伙食费:转伙食费,转住院费:转住院费,随心E购:随心E购,出院退款:出院退款,其他用途:其他用途" value=enum_good /]
    [@b.textfield name="detail_good" label="其他明细" value=detail_good required="false" maxlength="20"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
