[#ftl]
[@b.head/]
[@b.toolbar title="养老金信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(bankcard) theme="list"]
    [#if bankcard.persisted]
      [@b.field label="病人"]
        ${bankcard.inpatient.code} ${bankcard.inpatient.name}
        [@b.field label="当前余额"]${bankcard.balance}元[/@]
      [/@]
    [#else]
      [@b.textfield name="bankcard.inpatient.code" label="住院号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.textfield name="bankcard.bank" label="银行" value=bankcard.bank! required="true"/]
    [@b.textfield name="bankcard.cardNo" label="卡号" value=bankcard.cardNo! required="true"/]
    [@b.radios label="是否为存折" name="bankcard.bankbook"  items="1:是,0:否" value=bankcard.bankbook! /]
    [@b.date name="bankcard.createdOn" label="起始年月" value=bankcard.createdOn! format="date" required="true" /]
    [@b.textfield name="bankcard.initBalance" label="起始余额" value=bankcard.initBalance! required="true" comment="元"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
