[#ftl]
[@b.head/]
[@b.toolbar title="养护补贴信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(subsidy) theme="list"]
    [#if subsidy.persisted]
      [@b.field label="病人"]
        ${subsidy.inpatient.code} ${subsidy.inpatient.name}
        [@b.field label="当前余额"]${subsidy.balance}元[/@]
      [/@]
    [#else]
      [@b.textfield name="subsidy.inpatient.code" label="住院号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.date name="subsidy.createdOn" label="起始年月" value=subsidy.createdOn! format="yyyy-MM" required="true" /]
    [@b.textfield name="subsidy.initBalance" label="起始余额" value=subsidy.initBalance! required="true" comment="元"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
