[#ftl]
[@b.head/]
[@b.toolbar title="部门基本信息"]bar.addBack();[/@]
  [#assign sa][#if department.persisted]!update?id=${department.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="department.code" label="代码" value="${department.code!}" required="true" maxlength="10"/]
    [@b.textfield name="department.indexno" label="序号" value="${department.indexno!}" required="true" maxlength="20"/]
    [@b.textfield name="department.name" label="名称" value="${department.name!}" required="true" maxlength="80"/]
    [@b.select name="department.parent.id" label="上级部门" value=department.parent! items=parents required="false"/]
    [@b.startend label="有效期限"
      name="department.beginOn,department.endOn" required="true,false"
      start=department.beginOn end=department.endOn format="date"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
