[#ftl]
[@b.head/]
[@b.toolbar title="银行卡支出信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(bill) theme="list"]
    [#if bill.persisted]
      [@b.field label="病人"]
        ${bill.account.inpatient.code} ${bill.account.inpatient.name} ${bill.account.bank} ${bill.account.cardNo}
      [/@]
    [#else]
      [@b.textfield name="bill.account.cardNo" label="银行卡号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.textfield name="bill.amount" label="消费金额" value=bill.amount! required="true" maxlength="20" comment="元"/]
    [@b.date name="bill.payAt" label="支出时间" value=bill.payAt! format="datetime" required="true" /]
    [@b.radios label="消费明细" name="bill.expenses" items="转零用金:转零用金" value=bill.expenses! /]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
