[#ftl]
[@b.head/]
[@b.toolbar title="养护补贴入账信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(income) theme="list"]
    [#if income.persisted]
      [@b.field label="病人"]
        ${income.account.inpatient.code} ${income.account.inpatient.name}
      [/@]
    [#else]
      [@base.inpatient name="inpatient.id" value=(bill.account.inpatient)! label="病人" required="true" style="width:300px"/]
    [/#if]
    [@b.textfield name="income.amount" label="入账金额" value=income.amount! required="true" maxlength="20" comment="元"/]
    [@b.date name="payAt" label="入账时间" value=income.payAt! format="datetime" required="true" /]
    [@b.textfield name="income.channel" label="入账渠道" required="true" value=income.channel! style="width:100px"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
