[#ftl]
[@b.head/]
[@b.toolbar title="银行卡入账信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(income) theme="list"]
    [#if income.persisted]
      [@b.field label="病人"]
        ${income.account.inpatient.code} ${income.account.inpatient.name} ${income.account.bank} ${income.account.cardNo}
      [/@]
    [#else]
      [@b.textfield name="income.account.cardNo" label="银行卡号" value="" required="true" maxlength="10"/]
    [/#if]
    [@b.textfield name="income.amount" label="入账金额" value=income.amount! required="true" maxlength="20" comment="元"/]
    [@b.date name="income.payAt" label="入账时间" value=income.payAt! format="datetime" required="true" /]
    [@b.select name="income.category.id" label="入账类别" required="true" value=income.category! items=categories style="width:100px"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
