[@b.nav class="nav-tabs nav-tabs-compact"]
  [@b.navitem href="meal"]伙食费余额[/@]
  [@b.navitem href="meal-bill"]支出流水[/@]
  [@b.navitem href="meal-income"]入账明细[/@]
  [@b.navitem href="meal-stat"]每期汇总[/@]
  [@b.navitem href="meal-setting"]扣费设置[/@]
[/@]
