[#ftl]
[@b.head/]
[@b.toolbar title="修改性别类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(diseaseType) theme="list"]
    [@b.textfield name="diseaseType.code" label="代码" value="${diseaseType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="diseaseType.name" label="名称" value="${diseaseType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="diseaseType.enName" label="英文名称" value="${diseaseType.enName!}" maxlength="100"/]
    [@b.startend label="有效期限"
      name="diseaseType.beginOn,diseaseType.endOn" required="false,false"
      start=diseaseType.beginOn end=diseaseType.endOn format="date"/]
    [@b.textfield name="diseaseType.remark" label="备注" value="${diseaseType.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
